"""rename tables to lowercase

Revision ID: 00fc2a15927f
Revises: 051ddc806c9d
Create Date: 2026-05-10 23:42:39.907972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00fc2a15927f'
down_revision: Union[str, None] = '051ddc806c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Semantic_Analysis', 'semantic_analysis')
    op.rename_table('User', 'user')
    op.drop_table('post_movie')
    op.drop_index(op.f('ix_User_id'), table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_constraint(op.f('comment_post_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_profile_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comment_like_profile_id_fkey'), 'comment_like', type_='foreignkey')
    op.drop_constraint(op.f('comment_like_comment_id_fkey'), 'comment_like', type_='foreignkey')
    op.create_foreign_key(None, 'comment_like', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_like', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entity_relationship_log', 'sentiment_score',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.drop_constraint(op.f('entity_relationship_log_profile_id_fkey'), 'entity_relationship_log', type_='foreignkey')
    op.create_foreign_key(None, 'entity_relationship_log', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fav_genre_genre_id_fkey'), 'fav_genre', type_='foreignkey')
    op.drop_constraint(op.f('fav_genre_profile_id_fkey'), 'fav_genre', type_='foreignkey')
    op.create_foreign_key(None, 'fav_genre', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fav_genre', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fav_people_profile_id_fkey'), 'fav_people', type_='foreignkey')
    op.drop_constraint(op.f('fav_people_people_id_fkey'), 'fav_people', type_='foreignkey')
    op.create_foreign_key(None, 'fav_people', 'people', ['people_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fav_people', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('follow_following_id_fkey'), 'follow', type_='foreignkey')
    op.drop_constraint(op.f('follow_follower_id_fkey'), 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'profile', ['following_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow', 'profile', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interaction_profile_id_fkey'), 'interaction', type_='foreignkey')
    op.drop_constraint(op.f('interaction_post_id_fkey'), 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interaction', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('local_auth_user_id_fkey'), 'local_auth', type_='foreignkey')
    op.create_foreign_key(None, 'local_auth', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('movie_genre_genre_id_fkey'), 'movie_genre', type_='foreignkey')
    op.drop_constraint(op.f('movie_genre_movie_id_fkey'), 'movie_genre', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genre', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_genre', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('movie_staff_movie_id_fkey'), 'movie_staff', type_='foreignkey')
    op.drop_constraint(op.f('movie_staff_people_id_fkey'), 'movie_staff', type_='foreignkey')
    op.create_foreign_key(None, 'movie_staff', 'people', ['people_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_staff', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('post_profile_id_fkey'), 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profile_user_id_fkey'), 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('social_auth_user_id_fkey'), 'social_auth', type_='foreignkey')
    op.create_foreign_key(None, 'social_auth', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_auth', type_='foreignkey')
    op.create_foreign_key(op.f('social_auth_user_id_fkey'), 'social_auth', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key(op.f('profile_user_id_fkey'), 'profile', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(op.f('post_profile_id_fkey'), 'post', 'profile', ['profile_id'], ['id'])
    op.drop_column('post', 'movie_id')
    op.drop_constraint(None, 'movie_staff', type_='foreignkey')
    op.drop_constraint(None, 'movie_staff', type_='foreignkey')
    op.create_foreign_key(op.f('movie_staff_people_id_fkey'), 'movie_staff', 'people', ['people_id'], ['id'])
    op.create_foreign_key(op.f('movie_staff_movie_id_fkey'), 'movie_staff', 'movie', ['movie_id'], ['id'])
    op.drop_constraint(None, 'movie_genre', type_='foreignkey')
    op.drop_constraint(None, 'movie_genre', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genre_movie_id_fkey'), 'movie_genre', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('movie_genre_genre_id_fkey'), 'movie_genre', 'genre', ['genre_id'], ['id'])
    op.drop_constraint(None, 'local_auth', type_='foreignkey')
    op.create_foreign_key(op.f('local_auth_user_id_fkey'), 'local_auth', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key(op.f('interaction_post_id_fkey'), 'interaction', 'post', ['post_id'], ['id'])
    op.create_foreign_key(op.f('interaction_profile_id_fkey'), 'interaction', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key(op.f('follow_follower_id_fkey'), 'follow', 'profile', ['follower_id'], ['id'])
    op.create_foreign_key(op.f('follow_following_id_fkey'), 'follow', 'profile', ['following_id'], ['id'])
    op.drop_constraint(None, 'fav_people', type_='foreignkey')
    op.drop_constraint(None, 'fav_people', type_='foreignkey')
    op.create_foreign_key(op.f('fav_people_people_id_fkey'), 'fav_people', 'people', ['people_id'], ['id'])
    op.create_foreign_key(op.f('fav_people_profile_id_fkey'), 'fav_people', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'fav_genre', type_='foreignkey')
    op.drop_constraint(None, 'fav_genre', type_='foreignkey')
    op.create_foreign_key(op.f('fav_genre_profile_id_fkey'), 'fav_genre', 'profile', ['profile_id'], ['id'])
    op.create_foreign_key(op.f('fav_genre_genre_id_fkey'), 'fav_genre', 'genre', ['genre_id'], ['id'])
    op.drop_constraint(None, 'entity_relationship_log', type_='foreignkey')
    op.create_foreign_key(op.f('entity_relationship_log_profile_id_fkey'), 'entity_relationship_log', 'profile', ['profile_id'], ['id'])
    op.alter_column('entity_relationship_log', 'sentiment_score',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=True)
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.create_foreign_key(op.f('comment_like_comment_id_fkey'), 'comment_like', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key(op.f('comment_like_profile_id_fkey'), 'comment_like', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_profile_id_fkey'), 'comment', 'profile', ['profile_id'], ['id'])
    op.create_foreign_key(op.f('comment_post_id_fkey'), 'comment', 'post', ['post_id'], ['id'])
    op.create_table('Semantic_Analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Semantic_Analysis_pkey'))
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ci_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey')),
    sa.UniqueConstraint('ci_value', name=op.f('User_ci_value_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('post_movie',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('post_movie_movie_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('post_movie_post_id_fkey')),
    sa.PrimaryKeyConstraint('post_id', 'movie_id', name=op.f('post_movie_pkey'))
    )
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.rename_table('user', 'User')
    op.rename_table('semantic_analysis', 'Semantic_Analysis')
    # ### end Alembic commands ###