"""Add block table and refactor models

Revision ID: 36b77b456a9a
Revises: 9c406a606233
Create Date: 2026-05-19 14:16:27.638715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b77b456a9a'
down_revision: Union[str, None] = '9c406a606233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['persona.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_index(op.f('ix_block_blocked_id'), 'block', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_block_blocker_id'), 'block', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_blocker_id'), table_name='block')
    op.drop_index(op.f('ix_block_blocked_id'), table_name='block')
    op.drop_table('block')
    # ### end Alembic commands ###