"""update persona table

Revision ID: 53fa802cd776
Revises: 7de81b7eb40b
Create Date: 2026-05-15 10:29:12.346351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fa802cd776'
down_revision: Union[str, None] = '7de81b7eb40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 테이블명 변경 (데이터 보존)
    op.rename_table('profile', 'persona')
    
    # 2. 누락된 신규 컬럼 추가 및 속성 변경
    # 기존 데이터가 있을 수 있으므로 tag와 status는 임시 기본값 설정
    op.add_column('persona', sa.Column('tag', sa.String(length=10), server_default='0000', nullable=False))
    op.add_column('persona', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('persona', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=True))
    op.add_column('persona', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('persona', 'nickname', existing_type=sa.VARCHAR(length=50), nullable=False)

    # 3. Unique Constraint 새로 생성
    op.create_unique_constraint('uq_persona_nickname_tag', 'persona', ['nickname', 'tag'])

    # 4. 각 참조 테이블의 컬럼명 변경 (profile_id -> persona_id) 및 외래키 업데이트
    op.alter_column('comment', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('comment_profile_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    op.alter_column('comment_like', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('comment_like_profile_id_fkey'), 'comment_like', type_='foreignkey')
    op.create_foreign_key(None, 'comment_like', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    op.alter_column('entity_relationship_log', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('entity_relationship_log_profile_id_fkey'), 'entity_relationship_log', type_='foreignkey')
    op.create_foreign_key(None, 'entity_relationship_log', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    op.alter_column('fav_genre', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('fav_genre_profile_id_fkey'), 'fav_genre', type_='foreignkey')
    op.create_foreign_key(None, 'fav_genre', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    op.alter_column('fav_people', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('fav_people_profile_id_fkey'), 'fav_people', type_='foreignkey')
    op.create_foreign_key(None, 'fav_people', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    op.alter_column('interaction', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('interaction_profile_id_fkey'), 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    op.alter_column('post', 'profile_id', new_column_name='persona_id')
    op.drop_constraint(op.f('post_profile_id_fkey'), 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')

    # follow 테이블 (컬럼명은 기존과 동일하나, FK 제약조건 참조 대상이 변경됨)
    op.drop_constraint(op.f('follow_following_id_fkey'), 'follow', type_='foreignkey')
    op.drop_constraint(op.f('follow_follower_id_fkey'), 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'persona', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow', 'persona', ['following_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(op.f('post_profile_id_fkey'), 'post', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('post', 'persona_id', new_column_name='profile_id')

    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key(op.f('interaction_profile_id_fkey'), 'interaction', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interaction', 'persona_id', new_column_name='profile_id')

    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key(op.f('follow_follower_id_fkey'), 'follow', 'profile', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('follow_following_id_fkey'), 'follow', 'profile', ['following_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint(None, 'fav_people', type_='foreignkey')
    op.create_foreign_key(op.f('fav_people_profile_id_fkey'), 'fav_people', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fav_people', 'persona_id', new_column_name='profile_id')

    op.drop_constraint(None, 'fav_genre', type_='foreignkey')
    op.create_foreign_key(op.f('fav_genre_profile_id_fkey'), 'fav_genre', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fav_genre', 'persona_id', new_column_name='profile_id')

    op.drop_constraint(None, 'entity_relationship_log', type_='foreignkey')
    op.create_foreign_key(op.f('entity_relationship_log_profile_id_fkey'), 'entity_relationship_log', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entity_relationship_log', 'persona_id', new_column_name='profile_id')

    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.create_foreign_key(op.f('comment_like_profile_id_fkey'), 'comment_like', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comment_like', 'persona_id', new_column_name='profile_id')

    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_profile_id_fkey'), 'comment', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comment', 'persona_id', new_column_name='profile_id')

    op.drop_constraint('uq_persona_nickname_tag', 'persona', type_='unique')
    op.alter_column('persona', 'nickname', existing_type=sa.VARCHAR(length=50), nullable=True)
    op.drop_column('persona', 'deleted_at')
    op.drop_column('persona', 'status')
    op.drop_column('persona', 'profile_image_url')
    op.drop_column('persona', 'tag')

    op.rename_table('persona', 'profile')
    # ### end Alembic commands ###