"""remove is_main and preference_status from persona

Revision ID: 67844f046d6d
Revises: e2e54e57184d
Create Date: 2026-05-27 14:33:52.345722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67844f046d6d'
down_revision: Union[str, None] = 'e2e54e57184d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'is_main')
    op.drop_column('persona', 'preference_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('preference_status', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('is_main', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###