"""add trgm index to post title and content

Revision ID: 694987df1e6a
Revises: 67844f046d6d
Create Date: 2026-05-29 17:06:16.235127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694987df1e6a'
down_revision: Union[str, None] = '67844f046d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=False))
    op.create_index('ix_post_content_trgm', 'post', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index(op.f('ix_post_like_count'), 'post', ['like_count'], unique=False)
    op.create_index('ix_post_title_trgm', 'post', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_movie_title_trgm', 'movie', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_people_name_trgm', 'people', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_persona_nickname_trgm', 'persona', ['nickname'], unique=False, postgresql_using='gin', postgresql_ops={'nickname': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_persona_nickname_trgm', table_name='persona', postgresql_using='gin', postgresql_ops={'nickname': 'gin_trgm_ops'})
    op.drop_index('ix_people_name_trgm', table_name='people', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_movie_title_trgm', table_name='movie', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_post_title_trgm', table_name='post', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_post_like_count'), table_name='post')
    op.drop_index('ix_post_content_trgm', table_name='post', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_column('post', 'like_count')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    # ### end Alembic commands ###