"""update recommand models

Revision ID: 6e54293d8157
Revises: f918313296ae
Create Date: 2026-06-09 14:26:03.608895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e54293d8157'
down_revision: Union[str, None] = 'f918313296ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_relationship_log', 'weight')
    op.alter_column('genre', 'genre_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=False)
    op.drop_constraint(op.f('overview_movie_id_fkey'), 'overview', type_='foreignkey')
    op.create_foreign_key(None, 'overview', 'movie', ['movie_id'], ['id'])
    op.alter_column('person', 'person_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('person', 'job')
    op.drop_constraint(op.f('youtube_video_movie_id_fkey'), 'youtube_video', type_='foreignkey')
    op.create_foreign_key(None, 'youtube_video', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube_video', type_='foreignkey')
    op.create_foreign_key(op.f('youtube_video_movie_id_fkey'), 'youtube_video', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.add_column('person', sa.Column('job', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.alter_column('person', 'person_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'overview', type_='foreignkey')
    op.create_foreign_key(op.f('overview_movie_id_fkey'), 'overview', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.alter_column('genre', 'genre_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('entity_relationship_log', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###