"""fix user_table

Revision ID: 7de81b7eb40b
Revises: f8711d79f477
Create Date: 2026-05-14 09:53:51.690201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de81b7eb40b'
down_revision: Union[str, None] = 'f8711d79f477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_local_auth_email', 'local_auth', ['email'])
    op.create_unique_constraint('uq_social_auth_provider_email', 'social_auth', ['provider', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_auth_provider_email', 'social_auth', type_='unique')
    op.drop_constraint('uq_local_auth_email', 'local_auth', type_='unique')
    # ### end Alembic commands ###