"""update 260615

Revision ID: 8b6acfd73952
Revises: drop_entity_relationship_log
Create Date: 2026-06-15 15:26:17.126191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6acfd73952'
down_revision: Union[str, None] = 'drop_entity_relationship_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_daily_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'keyword', name='uq_search_stat_date_keyword')
    )
    op.create_index(op.f('ix_search_daily_stat_id'), 'search_daily_stat', ['id'], unique=False)
    op.create_index(op.f('ix_search_daily_stat_keyword'), 'search_daily_stat', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_daily_stat_stat_date'), 'search_daily_stat', ['stat_date'], unique=False)
    op.create_table('search_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_log_created_at'), 'search_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_log_id'), 'search_log', ['id'], unique=False)
    op.create_index(op.f('ix_search_log_keyword'), 'search_log', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_log_user_id'), 'search_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_log_user_id'), table_name='search_log')
    op.drop_index(op.f('ix_search_log_keyword'), table_name='search_log')
    op.drop_index(op.f('ix_search_log_id'), table_name='search_log')
    op.drop_index(op.f('ix_search_log_created_at'), table_name='search_log')
    op.drop_table('search_log')
    op.drop_index(op.f('ix_search_daily_stat_stat_date'), table_name='search_daily_stat')
    op.drop_index(op.f('ix_search_daily_stat_keyword'), table_name='search_daily_stat')
    op.drop_index(op.f('ix_search_daily_stat_id'), table_name='search_daily_stat')
    op.drop_table('search_daily_stat')
    # ### end Alembic commands ###