"""update table(Post)

Revision ID: 9c406a606233
Revises: 53fa802cd776
Create Date: 2026-05-15 11:40:33.356161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c406a606233'
down_revision: Union[str, None] = '53fa802cd776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('normalized_keyword', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_keyword')
    )
    op.create_table('like_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'target_type', 'target_id', name='uq_likelog_persona_target')
    )
    op.create_index('ix_likelog_target', 'like_log', ['target_type', 'target_id'], unique=False)
    op.create_table('post_hashtag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )
    op.create_table('post_mention',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'persona_id')
    )
    op.create_table('post_movie',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'movie_id')
    )
    op.create_table('comment_mention',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'persona_id')
    )
    op.drop_table('comment_like')
    op.drop_table('interaction')
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('is_spoiler', sa.SmallInteger(), nullable=True))
    op.add_column('comment', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_entity_log_target', 'entity_relationship_log', ['target_type', 'target_id'], unique=False)
    op.add_column('post', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('post', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('post', sa.Column('is_spoiler', sa.SmallInteger(), nullable=True))
    op.add_column('post', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('post_movie_id_fkey'), 'post', type_='foreignkey')
    op.drop_column('post', 'image_url')
    op.drop_column('post', 'movie_id')
    op.create_index('ix_semantic_target', 'semantic_analysis', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_semantic_target', table_name='semantic_analysis')
    op.add_column('post', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('post_movie_id_fkey'), 'post', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'status')
    op.drop_column('post', 'is_spoiler')
    op.drop_column('post', 'image_urls')
    op.drop_column('post', 'title')
    op.drop_index('ix_entity_log_target', table_name='entity_relationship_log')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'updated_at')
    op.drop_column('comment', 'status')
    op.drop_column('comment', 'is_spoiler')
    op.drop_column('comment', 'parent_id')
    op.create_table('interaction',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_analyzed', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('interaction_persona_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('interaction_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'persona_id', name=op.f('interaction_pkey'))
    )
    op.create_table('comment_like',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('comment_like_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('comment_like_persona_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'persona_id', name=op.f('comment_like_pkey'))
    )
    op.drop_table('comment_mention')
    op.drop_table('post_movie')
    op.drop_table('post_mention')
    op.drop_table('post_hashtag')
    op.drop_index('ix_likelog_target', table_name='like_log')
    op.drop_table('like_log')
    op.drop_table('hashtag')
    # ### end Alembic commands ###