"""create fav_movie table

Revision ID: e2e54e57184d
Revises: 93b632e25ddb
Create Date: 2026-05-24 00:32:32.467529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e54e57184d'
down_revision: Union[str, None] = '93b632e25ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_movie',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('persona_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_movie')
    # ### end Alembic commands ###