name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # main 브랜치로 push (merge) 될 때 동작
    paths-ignores: # 아래 파일은 제외
      - '**.md'
      - '.gitignore'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 우분투 사용
    steps:
    - name: Checkout code # 1. 깃허브 코드 다운
      uses: actions/checkout@v4

    - name: Login to Docker Hub # 2. 도커 허브 로그인
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push # 3. 도커 이미지 빌드하고 도커 허브로 push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/filma-backend:latest 
          ${{ secrets.DOCKER_USERNAME }}/filma-backend:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/filma-backend:1.${{ github.run_number }}

    - name: Checkout Helm Chart Repo
      uses: actions/checkout@v4 # helm repo 코드 다운
      with:
        repository: kakao4-KAKAMU/kakamu_helm # 헬름 차트 깃허브 레포
        token: ${{ secrets.HELM_REPO_TOKEN }} # 레포 권한이 있는 토큰
        path: helm-charts
        ref: dev # dev 브랜치를 checkout
          
    - name: Update Helm Values # 백엔드 values.yaml 이미지 태그값 검증 후 변경 + dev 브랜치로 push
      run: |
        cd helm-charts/environments/dev/back
        yq -i '.image.tag = "1.${{ github.run_number }}"' values.yaml
        
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add values.yaml
        
        if ! git diff --cached --quiet; then
          git commit -m "update backend image tag to 1.${{ github.run_number }}"
          git push origin HEAD:dev
        else
          echo "No changes to commit"
        fi        
        
        
